[[FFMPEG_nogpl]]
arch = "aarch64"
git-tree-sha1 = "dfd48dc687b0799497953ecb7b6b1878b0cb8f59"
os = "macos"

    [[FFMPEG_nogpl.download]]
    sha256 = "cd819d7b4615e02574777b9d1df0048219e99a13333cb09bebc9a934a4e20ba8"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.aarch64-apple-darwin.tar.gz"
[[FFMPEG_nogpl]]
arch = "aarch64"
git-tree-sha1 = "0ef6958ccec866327e4745068d664c01c5cc4157"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "0722326f16a935dbdcc933ab0b2fd3f4460250f9ad7602c2a8fb0089f91430d5"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.aarch64-linux-gnu.tar.gz"
[[FFMPEG_nogpl]]
arch = "aarch64"
git-tree-sha1 = "56a7a5f040e14700bd1c4ceb562d55ff9e12f71d"
libc = "musl"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "efbb730f4dbe2906f6ba684c0d955a9c30d52b486fba3ce1e74cf2a93744b72b"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.aarch64-linux-musl.tar.gz"
[[FFMPEG_nogpl]]
arch = "aarch64"
git-tree-sha1 = "837c93937225f5ea84a4a7d476ee291cc7702c90"
os = "freebsd"

    [[FFMPEG_nogpl.download]]
    sha256 = "81c11ed6bc866ed88931748e03945046d7ceda5a584c14b167cd4e6c0b62abbf"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.aarch64-unknown-freebsd.tar.gz"
[[FFMPEG_nogpl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3864752c278fc74eb3d6fcc266bc13d1d3153962"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "e4bbf901bae895080f25549afaf14cb53ebdb3c4d0ac19f57d107a8bac3318e3"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.armv6l-linux-gnueabihf.tar.gz"
[[FFMPEG_nogpl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a79532e340d8a7817fee5b83691ae463514f909c"
libc = "musl"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "8fa252cfef1699338166b604a68e929227f2106ecaa7495c9b84640637755400"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.armv6l-linux-musleabihf.tar.gz"
[[FFMPEG_nogpl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1394b4c06753f32fe4ddccb680443642314f6676"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "c0fa503c0e646688239ba71c20815be9a84085c69b481ea5687715925f44c7a1"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.armv7l-linux-gnueabihf.tar.gz"
[[FFMPEG_nogpl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9d67dd676c7d42dc02556f045513baee9ed46dfe"
libc = "musl"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "1e36b4c213a0ff1e431afbb7aafbfabd599b0824a7d79cd312f7cfc1cbf6e23e"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.armv7l-linux-musleabihf.tar.gz"
[[FFMPEG_nogpl]]
arch = "i686"
git-tree-sha1 = "dde823f9c3881e714958824df2a2173c88ed94a3"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "f6fb97ed9ac01efff7ce0a4bc72f5d9ea2409d5e1b17fb784df0786988dc45bc"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.i686-linux-gnu.tar.gz"
[[FFMPEG_nogpl]]
arch = "i686"
git-tree-sha1 = "c36f3d2011d97d7976ef32dce19513a305bbedb3"
libc = "musl"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "fe33723dd954e9ba2bb6e34c722b54b75abd80cde9df8d66b621aa5be27eead5"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.i686-linux-musl.tar.gz"
[[FFMPEG_nogpl]]
arch = "i686"
git-tree-sha1 = "f5d8dd8d90ce35993b8c0a7085efa8f3e1a64cfd"
os = "windows"

    [[FFMPEG_nogpl.download]]
    sha256 = "c968aff712f0a6d3c319a6cc4e284614e1db5c821427f145f0a87570cefe05aa"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.i686-w64-mingw32.tar.gz"
[[FFMPEG_nogpl]]
arch = "powerpc64le"
git-tree-sha1 = "31feefcaea758bfcfb9ed8aa983ddafe71bb1c1f"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "cd4fe18e8ebe0e10890c1fed249e097e05a014e97af641ac738c758d95be98e2"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.powerpc64le-linux-gnu.tar.gz"
[[FFMPEG_nogpl]]
arch = "riscv64"
git-tree-sha1 = "1124e3689c4eec176acb126490b02b35456ef667"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "ebe963b2b08213ec7c10398792069ef73cfe0b4ed16cfbb3b76e2083f9f733ee"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.riscv64-linux-gnu.tar.gz"
[[FFMPEG_nogpl]]
arch = "x86_64"
git-tree-sha1 = "d0ad86cbbd6cb7fab7e3c1f0295b7d074e67e370"
os = "macos"

    [[FFMPEG_nogpl.download]]
    sha256 = "c06b0d695d13a2b192040af5b9b86c86801c1f5f4b7ecd9f9930f0a27b8616cf"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.x86_64-apple-darwin.tar.gz"
[[FFMPEG_nogpl]]
arch = "x86_64"
git-tree-sha1 = "77418bb5f0b31bd9ca347ba12c99584f1e101f50"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "033764cab79f72e0ed10be55d4c95e14a0e9ee7c08c8182a278b05dfc92b8ebb"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.x86_64-linux-gnu.tar.gz"
[[FFMPEG_nogpl]]
arch = "x86_64"
git-tree-sha1 = "f1a9b1b56121bbf8654aa967e477d7798aa1f9c1"
libc = "musl"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "757b1077779e1a7a28bb433a73424408d15ac053cf053e0edab4bce41c0d78af"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.x86_64-linux-musl.tar.gz"
[[FFMPEG_nogpl]]
arch = "x86_64"
git-tree-sha1 = "7eaaf8ca82e3a47ced8f4f6ca4b397501a78d09a"
os = "freebsd"

    [[FFMPEG_nogpl.download]]
    sha256 = "d8823d0e3307728ccf6ae7d0b9a661503115894f6452441e53034ac9fe8d1635"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.x86_64-unknown-freebsd.tar.gz"
[[FFMPEG_nogpl]]
arch = "x86_64"
git-tree-sha1 = "d8eff1587f02db0ae712846f929ec07bd93b8f28"
os = "windows"

    [[FFMPEG_nogpl.download]]
    sha256 = "8aa20bfe910eb71f4fe54e85364e1e63893c31faf61e5e3cc9de37c067f664e0"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v9.0.0+0/FFMPEG_nogpl.v9.0.0.x86_64-w64-mingw32.tar.gz"
