[[FFMPEG_nogpl]]
arch = "aarch64"
git-tree-sha1 = "057845d8b80b725124fbaf9a8a020d1103dbfc42"
os = "macos"

    [[FFMPEG_nogpl.download]]
    sha256 = "001bb18e55e02906e02263ed0d7307a3fa905ad21b2762d7e79899e268bcbb9b"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.aarch64-apple-darwin.tar.gz"
[[FFMPEG_nogpl]]
arch = "aarch64"
git-tree-sha1 = "35851d552fd74ffeb99b8435ae274a17d2be7444"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "1a65298eab691cd909867c433704c4c27fe1112d99dd32e8429db333d0bbe53e"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.aarch64-linux-gnu.tar.gz"
[[FFMPEG_nogpl]]
arch = "aarch64"
git-tree-sha1 = "234a55395d48ab38de1950c51922929e99ab88fc"
libc = "musl"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "4ee77028958eff215a576a585df294dc738162bc2bf0f62aaa5d8ad7e6fbdb10"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.aarch64-linux-musl.tar.gz"
[[FFMPEG_nogpl]]
arch = "aarch64"
git-tree-sha1 = "caf6d5c04078931ddeb07e0093f396898d5a991d"
os = "freebsd"

    [[FFMPEG_nogpl.download]]
    sha256 = "b235220840db5a241cc6c2ba98df4344e6266e5617fb791434a696a06474ccd8"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.aarch64-unknown-freebsd.tar.gz"
[[FFMPEG_nogpl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "537c92efff1834b4ebe96fd35dbc070109b1f562"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "551fcf7944e887eca24818acf9145e608ed8c197ac4e70f65617cfb6fb4f7628"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.armv6l-linux-gnueabihf.tar.gz"
[[FFMPEG_nogpl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "806ebd22f66a5e385996bfdcb709ddcf9f3e4e45"
libc = "musl"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "4d3ede72335c7269a90ee71c216d8a092ff31ca6144a3c4c757d296b93ea499e"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.armv6l-linux-musleabihf.tar.gz"
[[FFMPEG_nogpl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8b530b9ecae4fffe47788260909c6172a2a85658"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "d6c50a009b7cf7564e0e64d2f170507b8568c601587a6e15399788b18b76b135"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.armv7l-linux-gnueabihf.tar.gz"
[[FFMPEG_nogpl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3cdb7eee52ca7ea18565a3947c08281e45c9675f"
libc = "musl"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "103137baebdfbc98f28239b87b3b30e654859fc2e3124950cc525e1ececff6d7"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.armv7l-linux-musleabihf.tar.gz"
[[FFMPEG_nogpl]]
arch = "i686"
git-tree-sha1 = "a07b8d888fe88fee96ff545d5ac984ae1a409134"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "19f5f3fdfeedac0768b53ff2492bc7c614cfd2ddcf2f9f40c51e7aca09e69122"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.i686-linux-gnu.tar.gz"
[[FFMPEG_nogpl]]
arch = "i686"
git-tree-sha1 = "83726d09c7ca8b53178a53c77379ea2b7cb97ca9"
libc = "musl"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "ed309cdd68eec11c7b38c64f7b5907c7c4086171006d1034da08fa23bddaeb53"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.i686-linux-musl.tar.gz"
[[FFMPEG_nogpl]]
arch = "i686"
git-tree-sha1 = "68fb41a12a0ebb2316737baf45d66d3da1b6a386"
os = "windows"

    [[FFMPEG_nogpl.download]]
    sha256 = "0ae49882fa85f89ad13672c12b7812d1fd5668d1faca47617eaa3303d1a0cf7f"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.i686-w64-mingw32.tar.gz"
[[FFMPEG_nogpl]]
arch = "powerpc64le"
git-tree-sha1 = "e6c8f8e748dcafb88e696fb6aed5f8717be4d427"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "6ac0920436d48e59a3cead212ca0cbb3cf92d0f2bb1cc04e7957432baa49593a"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.powerpc64le-linux-gnu.tar.gz"
[[FFMPEG_nogpl]]
arch = "riscv64"
git-tree-sha1 = "8424c1f60d7806dc843997d83dc5567c7e753331"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "f327a05510ea32957adb4ce10c859168a57e6df3d34bd5ace9b4a3802c1169a9"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.riscv64-linux-gnu.tar.gz"
[[FFMPEG_nogpl]]
arch = "x86_64"
git-tree-sha1 = "95c18b4b01920b7b347f1b3bba7f9b663d4dcc74"
os = "macos"

    [[FFMPEG_nogpl.download]]
    sha256 = "91568d54c302911f850496abd42e0528c95070b6b13c7ca4f5ac4948b3132ffd"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.x86_64-apple-darwin.tar.gz"
[[FFMPEG_nogpl]]
arch = "x86_64"
git-tree-sha1 = "c4beea764dc6320fcd8b3ce4da61dd6793d6fc62"
libc = "glibc"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "4de335718c5f5365d2c7ac2f54886cf0bb1b30636d23b726e8120e672042d59e"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.x86_64-linux-gnu.tar.gz"
[[FFMPEG_nogpl]]
arch = "x86_64"
git-tree-sha1 = "baaf6bfd72af61db1648a23f6cf39c9f823d58fe"
libc = "musl"
os = "linux"

    [[FFMPEG_nogpl.download]]
    sha256 = "c0cd4dc8b5d92145f8c9cc5e8ca07b1becfb71ae0b35c488ef7feb29fefb9862"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.x86_64-linux-musl.tar.gz"
[[FFMPEG_nogpl]]
arch = "x86_64"
git-tree-sha1 = "daeabf38c2b816b9a476ba3ccea19161b582374a"
os = "freebsd"

    [[FFMPEG_nogpl.download]]
    sha256 = "160f5cf85ed94c01cd517525be150720ebe8d9e78b2064342de767b7ab652f00"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.x86_64-unknown-freebsd.tar.gz"
[[FFMPEG_nogpl]]
arch = "x86_64"
git-tree-sha1 = "e82b3e8169557ff5b9ef39882c8fe65e7e7c9024"
os = "windows"

    [[FFMPEG_nogpl.download]]
    sha256 = "6550f94513896e8cecf1e80e55d6345b7d978872f0501c01837488c2d9155039"
    url = "https://github.com/JuliaBinaryWrappers/FFMPEG_nogpl_jll.jl/releases/download/FFMPEG_nogpl-v8.1.2+0/FFMPEG_nogpl.v8.1.2.x86_64-w64-mingw32.tar.gz"
