# Autogenerated wrapper script for FFMPEG_nogpl_jll for aarch64-apple-darwin
export ffmpeg, ffprobe, libavcodec, libavdevice, libavfilter, libavformat, libavutil, libswresample, libswscale

using libass_jll
using FriBidi_jll
using FreeType2_jll
using LAME_jll
using libvorbis_jll
using libaom_jll
using Ogg_jll
using Bzip2_jll
using Zlib_jll
using OpenSSL_jll
using Opus_jll
using PCRE2_jll
JLLWrappers.@generate_wrapper_header("FFMPEG_nogpl")
JLLWrappers.@declare_library_product(libavcodec, "@rpath/libavcodec.63.dylib")
JLLWrappers.@declare_library_product(libavdevice, "@rpath/libavdevice.63.dylib")
JLLWrappers.@declare_library_product(libavfilter, "@rpath/libavfilter.12.dylib")
JLLWrappers.@declare_library_product(libavformat, "@rpath/libavformat.63.dylib")
JLLWrappers.@declare_library_product(libavutil, "@rpath/libavutil.61.dylib")
JLLWrappers.@declare_library_product(libswresample, "@rpath/libswresample.7.dylib")
JLLWrappers.@declare_library_product(libswscale, "@rpath/libswscale.10.dylib")
JLLWrappers.@declare_executable_product(ffmpeg)
JLLWrappers.@declare_executable_product(ffprobe)
function __init__()
    JLLWrappers.@generate_init_header(libass_jll, FriBidi_jll, FreeType2_jll, LAME_jll, libvorbis_jll, libaom_jll, Ogg_jll, Bzip2_jll, Zlib_jll, OpenSSL_jll, Opus_jll, PCRE2_jll)
    JLLWrappers.@init_library_product(
        libavcodec,
        "lib/libavcodec.63.1.102.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libavdevice,
        "lib/libavdevice.63.1.102.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libavfilter,
        "lib/libavfilter.12.1.102.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libavformat,
        "lib/libavformat.63.1.102.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libavutil,
        "lib/libavutil.61.1.102.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libswresample,
        "lib/libswresample.7.1.102.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libswscale,
        "lib/libswscale.10.1.102.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        ffmpeg,
        "bin/ffmpeg",
    )

    JLLWrappers.@init_executable_product(
        ffprobe,
        "bin/ffprobe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
